car="bmw"
sport="judo"
name="giga"
username="bucxrikidze"
age=11
print(car)
print(type(car))
print(sport)
print(type(sport))
print(name)
print(type(name))
print(username)
print(type(username))
print(age)
print(type(age))