print(5 < 5) # False
print(9 > 8) # True
print(8 < 6) # False
print(7 > 6) # True
print(4 < 5) # False
print(9 > 4) # True
print(7 < 6) # False
print(7 > 1) # True
print(1 < 0) # False
print(1 > 0) # True